//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhlybovExam.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prog2Entities : DbContext
    {
        public prog2Entities()
            : base("name=prog2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ClientUser> ClientUser { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<ReparePhone> ReparePhone { get; set; }
        public virtual DbSet<RepareSklad> RepareSklad { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SkladMaterial> SkladMaterial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypePhone> TypePhone { get; set; }
        public virtual DbSet<TypeRepare> TypeRepare { get; set; }
    }
}
