//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhlybovExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepareSklad
    {
        public int id_repsklad { get; set; }
        public int id_clientuser { get; set; }
        public int id_phone { get; set; }
    
        public virtual ClientUser ClientUser { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
