//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhlybovExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReparePhone
    {
        public int id_repphone { get; set; }
        public int id_clientuser { get; set; }
        public int id_phone { get; set; }
        public int id_typerepare { get; set; }
        public string Price { get; set; }
    
        public virtual TypeRepare TypeRepare { get; set; }
    }
}
