//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhlybovExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladMaterial
    {
        public int id_skladmat { get; set; }
        public int id_typematerial { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
    }
}
