//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhlybovExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeRepare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeRepare()
        {
            this.ReparePhone = new HashSet<ReparePhone>();
        }
    
        public int id_typerepare { get; set; }
        public string Name { get; set; }
        public int id_typematerial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReparePhone> ReparePhone { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
    }
}
